### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by emigdioz** [emigdioz/LeafGP#1]
Features and enhancements
- [ ] Data exploration page (Express), reorganize visual elements.
- [ ] Implement Processing section.
- [ ] Implement Autotuning functionality in Settings (Express).
- [ ] Data partitions should be saved separately.
- [x] Load population functionality missing.
- [x] Saving container formar definition and implementation (it should save data, partitions, settings, results).
- [ ] Settings page (Advanced) Functions section, drag&drop should be allowed also multiple items plus double click insertion.
- [ ] Settings page (Advanced) Fitness section is missing.
- [x] Missing local fitness calculation and make optional OpenCL library linking.
- [x] Rearrange visual elements in GP page (Express).
- [x] Results page (Express) is missing.
- [ ] Results page (Advanced) Summary section, Information is missing.
- [x] Results page (Advanced) Saving section is missing. Depends on the container format implementation.
- [ ] Unifinished Results page (Advanced) Report section.
- [ ] Implement Levenberg-marquardt as LS operator.
- [ ] Add LS parameters.
